name: Generate Tag
on:
  workflow_dispatch:  # This will enable manual runs only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Replace with the desired Node.js version (e.g., '18.x' or '18.0.0').

    - name: Install dependencies
      run: npm install

    - name: Generate Tag Version
      id: get_version
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Create and Push Tag
      run: |
        # Get the version from the previous step's output
        VERSION=${{ steps.get_version.outputs.version }}
        
        # Set the tag to the version from package.json
        git tag $VERSION
        git push origin $VERSION
